name: Auto Merge on Pull Request

on:
  pull_request:
    branches:
      - main # Or your main branch name
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review # Optional: If you use "Ready for Review" feature

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state == 'open' && github.event.pull_request.draft == false && github.event.pull_request.merged == false # Check if PR is open, not a draft, and not already merged
    permissions:
      pull-requests: write # Needed to merge the PR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git identity (Optional, but recommended)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if there are conflicts (Optional, but recommended)
        run: |
          if git status --porcelain | grep -q "^C"; then
            echo "::error::Pull request has merge conflicts. Please resolve them."
            exit 1
          fi

      - name: Merge pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_request_number = context.issue.number;
            return github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_request_number,
              merge_method: 'rebase' # Or 'merge' or 'squash'
            });

